### PR TITLE
Add note on Hierarchical Namespace for Azure Storage Account

### LINKED ISSUE #126: Temp path issue for Windows worker downloading from Azure Blob
# Expectation / Proposal

Cross-linking here since this since I'm a bit unsure where to report: https://github.com/PrefectHQ/prefect/issues/11211

# Traceback / Example

- [ ] I would like to [help contribute](https://PrefectHQ.github.io/prefect-azure/#contributing) a pull request to resolve this!

### PR DESCRIPTION
**Pull request by thomasfrederikhoeck**
Add note on Hierarchical Namespace for Azure Storage Account. I ran into a hard to understand issue since the code was being downloaded from a Blob Container with Hierarchical Namespace which meant that `.list_blobs()` had both the folder name and file name as seperate files it tried to download. An idea for another addition could be a check to see if the Storage Account has Hierarchical Namespace enabled before listing Blobs.

Closes #126
Closes https://github.com/PrefectHQ/prefect/issues/11211

### Screenshots
image

### Checklist

- [ ] References any related issue by including "Closes #<Issue Number>" or "Closes <Issue URL>".
  - If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect-azure/issues/new/choose) first.
- [ ] Includes tests or only affects documentation.
- [ ] Passes `pre-commit` checks.
  - Run `pre-commit install && pre-commit run --all` locally for formatting and linting.
- [ ] Includes screenshots of documentation updates.
  - Run `mkdocs serve` view documentation locally.
- [ ] Summarizes PR's changes in [CHANGELOG.md](https://github.com/PrefectHQ/prefect-azure/blob/main/CHANGELOG.md)

### CODE REVIEW

**Comment by thomasfrederikhoeck** [comment]
Pinging for review @zzstoatzz  :-)

**Review by zzstoatzz — APPROVED** [review]
thank you!

**Comment by thomasfrederikhoeck** [comment]
@zzstoatzz No problem. Does it need a second approval?

**Comment by zzstoatzz** [comment]
> @zzstoatzz No problem. Does it need a second approval?

nope i just needed to approve the workflow to run - running now!

**Pull request merged**
